# Generated by Django 6.0.2 on 2026-03-31 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_practice_quizzes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_count', models.IntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('bulk_upload', 'Bulk Upload'), ('ai_generated', 'AI Generated')], default='manual', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_batches', to='quizapp.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel')], default='csv', max_length=10)),
                ('file_size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('upload_pending', 'Upload Pending'), ('processing', 'Processing'), ('validated', 'Validated'), ('preview_review', 'Preview Review'), ('committed', 'Committed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='upload_pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('error_report', models.TextField(blank=True)),
                ('error_file_path', models.CharField(blank=True, max_length=500)),
                ('temp_file_path', models.CharField(blank=True, max_length=500)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='quizapp.quiz')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('quiz_create', 'Quiz Created'), ('quiz_update', 'Quiz Updated'), ('quiz_delete', 'Quiz Deleted'), ('upload_start', 'Upload Started'), ('upload_commit', 'Upload Committed'), ('upload_rollback', 'Upload Rolled Back'), ('question_batch_delete', 'Question Batch Deleted'), ('quiz_version_create', 'Quiz Version Created')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.quiz')),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.uploadsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuizVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quizapp.quiz')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('quiz', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status', '-uploaded_at'], name='quizapp_upl_status_e2aa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='quizapp_upl_uploade_eef619_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='quizapp_adm_admin_u_41f215_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='quizapp_adm_action_5f9f2b_idx'),
        ),
    ]
