# Generated by Django 6.0.3 on 2026-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_questionbatch_uploadsession_adminauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
